root -l -b -q "./fragment/frag_tofw_calib.C(0,13)" >/dev/null & echo "done 0"
root -l -b -q "./fragment/frag_tofw_calib.C(1,13)" >/dev/null & echo "done 1"
root -l -b -q "./fragment/frag_tofw_calib.C(2,13)" >/dev/null & echo "done 2"
#root -l -b -q "./fragment/frag_tofw_calib.C(0,12)" >/dev/null & echo "done 3"
#root -l -b -q "./fragment/frag_tofw_calib.C(1,12)" >/dev/null & echo "done 4"
#root -l -b -q "./fragment/frag_tofw_calib.C(2,12)" >/dev/null & echo "done 5"
#root -l -b -q "./fragment/frag_tofw_calib.C(0,122)">/dev/null & echo "done 6"
#root -l -b -q "./fragment/frag_tofw_calib.C(1,122)">/dev/null & echo "done 7"
#root -l -b -q "./fragment/frag_tofw_calib.C(2,122)">/dev/null & echo "done 8"
